version: 1
detalle: str
MongoDBProcessor:
  db: dyn
  collections:
    # info collections
    cliente: registro
    auditoria: registro
    categoria: registro
    cliente_auditoria: registro
    cliente_categoria: registro
    auditoria_categoria: registro
    foto_cargada: registro
    # agg collections
    fotos_requeridas_por_cliente: cliente_categoria
    fotos_registradas_por_auditoria: foto_cargada
    resumen: fotos_registradas_por_auditoria




